---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(usethis)
library(fredr)
library(hrbrthemes)
library(extrafont)
library(zoo)
library(purrr)
library(rdbnomics)
library(ustfd)
library(imf.data)
library(BISdata)
library(ggrepel)
```

```{r}
#extrafont::font_import()
extrafont::loadfonts(device="win")
```

# Playing with Fredr

```{r}
important_dates <- as_date(c("2021-01-20","2022-08-09", "2022-08-16", "2025-01-20", "2025-04-02"))
```
```{r}
plot_manufacturing_function <- function(data, labs, dates){ #manufacturing for now
  data %>% 
    filter(date > "2021-01-19") %>% 
    ggplot(aes(x = date)) +
    geom_point(aes(y = value)) +
    geom_point(aes(y = value_10yravg), color = "green") +
    geom_point(aes(y = value_1yravg), color = "blue") +
    geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7"
    geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) +
    geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) +
    scale_color_manual(values = c(
      `Current Data` = "black",
      `Long Term (10year) Average` = "green",
      `Short Term (1year) Average` = "blue"
      )) +
    geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
    labs +
    scale_y_comma() +
    theme(panel.grid.major = element_line(color = "black",
                                        size = 0.5,
                                        linetype = 2))
}
```
```{r}
plot_manufacturing_function(MANEMP, labs(x = "Monthly Reporting", y = "Thousands of Persons, Seasonally Adjusted", title = "Manufacturing Employment", caption = "All Employees", color = "Manufacturing Employment", important_dates))
```


# Manufacturing Data

```{r Employment} 
MANEMP <- fredr(
  series_id = "MANEMP",
  observation_start = as.Date("2010-01-01"),
  frequency = "q",
  aggregation_method = "sum"
) 
MANEMP$date <- ymd(MANEMP$date)
MANEMP$date <- c(MANEMP$date[-1], NA)

MANEMP2 <- fredr(
  series_id = "MANEMP",
  observation_start = as.Date("2010-01-01")
) 
MANEMP2$date <- ymd(MANEMP2$date)

MANEMP <- MANEMP %>% 
  select(-realtime_start, -realtime_end) %>% 
  mutate(value_10yravg = rollmean(value, k = 30, fill = NA, align = "right")) %>%
  mutate(sd_10yravg = rollapply(value, width = 30, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(value_2yravg = rollmean(value, k = 6, fill = NA, align = "right")) %>% 
  mutate(sd_2yravg = rollapply(value, width = 6, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>% 
  mutate(zscore_2yravg = ((value - value_2yravg)/sd_2yravg))

 
MANEMP %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = value)) +
  geom_point(aes(y = value_10yravg), color = "green") +
  geom_point(aes(y = value_2yravg), color = "blue") +
  geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7"
  geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) +
  geom_line(aes(y = value_2yravg, color = "Short Term (2year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Current Data` = "black",
    `Long Term (10year) Average` = "green",
    `Short Term (2year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Monthly Reporting", y = "Thousands of Persons, Seasonally Adjusted", title = "Manufacturing Employment", caption = "All Employees", color = "Manufacturing Employment") +
  scale_y_comma()

MANEMP %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = zscore_10yravg), color = "green") +
  geom_point(aes(y = zscore_2yravg), color = "blue") +
  geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) +
  geom_line(aes(y = zscore_2yravg, color = "Z score (2year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Z score (10year) Average` = "green",
    `Z score (2year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Date", y = "Z score", title = "Manufacturing Employment Z score", caption = "All Employees", color = "Near or Long Term Z score") 
  
```


```{r New Orders}
AMTMNO <- fredr(
  series_id = "AMTMNO",
  observation_start = as.Date("2010-01-01")
) 
AMTMNO$date <- ymd(AMTMNO$date)

AMTMNO <- AMTMNO %>% 
  select(-realtime_start, -realtime_end) %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>% 
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>% 
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>% 
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg))
 
AMTMNO %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = value)) +
  geom_point(aes(y = value_10yravg), color = "green") +
  geom_point(aes(y = value_1yravg), color = "blue") +
  geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7"
  geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) +
  geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Current Data` = "black",
    `Long Term (10year) Average` = "green",
    `Short Term (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Monthly Reporting", y = "Millions of Dollars, Seasonally Adjusted", title = "Manufacturer's New Orders", caption = "Total Manufacturing")  +
  scale_y_comma()

AMTMNO %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = zscore_10yravg), color = "green") +
  geom_point(aes(y = zscore_1yravg), color = "blue") +
  geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) +
  geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Z score (10year) Average` = "green",
    `Z score (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Date", y = "Z score", title = "Manufacturer's New Orders Z score", caption = "All Employees", color = "Near or Long Term Z score") 
```
```{r Gross Output Dollars}
GOMA <- fredr(
  series_id = "GOMA",
  observation_start = as.Date("2010-01-01")
) 
GOMA$date <- ymd(GOMA$date)

GOMA <- GOMA %>% 
  select(-realtime_start, -realtime_end) %>% 
  mutate(month_seq = purrr::map(date, ~ seq(.x, by = "1 month", length.out = 3))) %>%
  unnest(month_seq) %>%
  select(-date) %>% 
  rename(date = month_seq) %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>% 
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>% 
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>% 
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg))
 
GOMA %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = value)) +
  geom_point(aes(y = value_10yravg), color = "green") +
  geom_point(aes(y = value_1yravg), color = "blue") +
  geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7"
  geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) +
  geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Current Data` = "black",
    `Long Term (10year) Average` = "green",
    `Short Term (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Quarterly Reporting", y = "Billions of Dollars, Seasonally Adjusted", title = "Manufacturing Gross Output", caption = "Changed to Monthly for Consistency")  +
  scale_y_comma()

GOMA %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = zscore_10yravg), color = "green") +
  geom_point(aes(y = zscore_1yravg), color = "blue") +
  geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) +
  geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Z score (10year) Average` = "green",
    `Z score (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Date", y = "Z score", title = "Manufacturing Gross Output Z score", caption = "Changed to Monthly for Consistency", color = "Near or Long Term Z score") 


```
```{r Shipments}
AMTMVS <- fredr(
  series_id = "AMTMVS",
  observation_start = as.Date("2010-01-01")
) 
AMTMVS$date <- ymd(AMTMVS$date)

AMTMVS <- AMTMVS %>% 
  select(-realtime_start, -realtime_end) %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>% 
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>% 
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>% 
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg))
 
AMTMVS %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = value)) +
  geom_point(aes(y = value_10yravg), color = "green") +
  geom_point(aes(y = value_1yravg), color = "blue") +
  geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7"
  geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) +
  geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Current Data` = "black",
    `Long Term (10year) Average` = "green",
    `Short Term (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Monthly Reporting", y = "Millions of Dollars, Seasonally Adjusted", title = "Manufacturer's Value of Shipments", caption = "Total Manufacturing") +
  scale_y_comma()

AMTMVS %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = zscore_10yravg), color = "green") +
  geom_point(aes(y = zscore_1yravg), color = "blue") +
  geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) +
  geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Z score (10year) Average` = "green",
    `Z score (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Date", y = "Z score", title = "Manufacturer's Value of Shipments Z score", caption = "Total Manufacturing", color = "Near or Long Term Z score") 
```
```{r Industrial Production}
IPMAN <- fredr(
  series_id = "IPMAN",
  observation_start = as.Date("2010-01-01")
) 
IPMAN$date <- ymd(IPMAN$date)

IPMAN <- IPMAN %>% 
  select(-realtime_start, -realtime_end) %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>% 
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>% 
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>% 
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg))
 
IPMAN %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = value)) +
  geom_point(aes(y = value_10yravg), color = "green") +
  geom_point(aes(y = value_1yravg), color = "blue") +
  geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7"
  geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) +
  geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Current Data` = "black",
    `Long Term (10year) Average` = "green",
    `Short Term (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Monthly Reporting", y = "Units, Not Seasonally Adjusted", title = "Manufacturing Production", caption = "Index 2017 = 100") +
  scale_y_comma()

IPMAN %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = zscore_10yravg), color = "green") +
  geom_point(aes(y = zscore_1yravg), color = "blue") +
  geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) +
  geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Z score (10year) Average` = "green",
    `Z score (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Date", y = "Z score", title = "Manufacturing Production Z score", caption = "Index 2017 = 100", color = "Near or Long Term Z score") 
```

```{r Industrial Capacity}
CAPGMFS <- fredr(
  series_id = "CAPGMFS",
  observation_start = as.Date("2010-01-01")
) 
CAPGMFS$date <- ymd(CAPGMFS$date)

CAPGMFS <- CAPGMFS %>% 
  select(-realtime_start, -realtime_end) %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>% 
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>% 
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>% 
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg))
 
CAPGMFS %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = value)) +
  geom_point(aes(y = value_10yravg), color = "green") +
  geom_point(aes(y = value_1yravg), color = "blue") +
  geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7"
  geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) +
  geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Current Data` = "black",
    `Long Term (10year) Average` = "green",
    `Short Term (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Monthly Reporting", y = "Units, Seasonally Adjusted", title = "Manufacturing Industrial Capacity", caption = "Index 2017 = 100") +
  scale_y_comma()

CAPGMFS %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = zscore_10yravg), color = "green") +
  geom_point(aes(y = zscore_1yravg), color = "blue") +
  geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) +
  geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Z score (10year) Average` = "green",
    `Z score (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Date", y = "Z score", title = "Manufacturing Industrial Capacity Z score", caption = "Index 2017 = 100", color = "Near or Long Term Z score") 
```

```{r Manufacturing Factory Investment}
C307RX1Q020SBEA <- fredr(
  series_id = "C307RX1Q020SBEA",
  observation_start = as.Date("2010-01-01")
) 
C307RX1Q020SBEA$date <- ymd(C307RX1Q020SBEA$date)

C307RX1Q020SBEA <- C307RX1Q020SBEA %>% 
  select(-realtime_start, -realtime_end) %>% 
  mutate(month_seq = purrr::map(date, ~ seq(.x, by = "1 month", length.out = 3))) %>%
  unnest(month_seq) %>%
  select(-date) %>% 
  rename(date = month_seq) %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>% 
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>% 
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>% 
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg))
 
C307RX1Q020SBEA %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = value)) +
  geom_point(aes(y = value_10yravg), color = "green") +
  geom_point(aes(y = value_1yravg), color = "blue") +
  geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7"
  geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) +
  geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Current Data` = "black",
    `Long Term (10year) Average` = "green",
    `Short Term (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Quarterly Reporting", y = "Billions of Chained 2017 Dollars", title = "Real Private Fixed Investment into Nonresidential\nManufacturing Structures (i.e. Factories)", caption = "Seasonally Adjusted Annual Rate") +
  scale_y_comma()

C307RX1Q020SBEA %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = zscore_10yravg), color = "green") +
  geom_point(aes(y = zscore_1yravg), color = "blue") +
  geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) +
  geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Z score (10year) Average` = "green",
    `Z score (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Date", y = "Z score", title = "Real Private Fixed Investment into Nonresidential\nManufacturing Structures Z Score", caption = "Manufacturing Factory Investment", color = "Near or Long Term Z score") 

```







```{r PPI}
# Don't use this is a proxy for inflation
PCUOMFGOMFG <- fredr(
  series_id = "PCUOMFGOMFG",
  observation_start = as.Date("2010-01-01")
) 
PCUOMFGOMFG$date <- ymd(PCUOMFGOMFG$date)

PCUOMFGOMFG <- PCUOMFGOMFG %>% 
  select(-realtime_start, -realtime_end) %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>% 
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>% 
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>% 
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg))
 
PCUOMFGOMFG %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = value)) +
  geom_point(aes(y = value_10yravg), color = "green") +
  geom_point(aes(y = value_1yravg), color = "blue") +
  geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7"
  geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) +
  geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Current Data` = "black",
    `Long Term (10year) Average` = "green",
    `Short Term (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Monthly Reporting", y = "Units, Not Seasonally Adjusted", title = "Manufacturing Producer Price Index", caption = "Index Dec 1984 = 100") +
  scale_y_comma()

PCUOMFGOMFG %>% 
  filter(date > "2021-01-19") %>% 
  ggplot(aes(x = date)) +
  geom_point(aes(y = zscore_10yravg), color = "green") +
  geom_point(aes(y = zscore_1yravg), color = "blue") +
  geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) +
  geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) +
  scale_color_manual(values = c(
    `Z score (10year) Average` = "green",
    `Z score (1year) Average` = "blue"
  )) +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1) +
  labs(x = "Date", y = "Z score", title = "Manufacturing Producer Price Index Z score", caption = "Index Dec 1984 = 100", color = "Near or Long Term Z score") 
```

```{r}
ism_pmi <- rdb(ids = "ISM/pmi/pm")
ism_pmi$period <- ymd(ism_pmi$period)
ism_pmi <- ism_pmi %>% 
  unite(series_id, c(provider_code, series_name, series_code), sep = "") %>% 
  select(-Frequency, -dataset_code, -frequency, -original_value, -original_period, -dataset_name, -indexed_at, -`@frequency`) %>% 
  rename(date = period) %>% 
  # mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>% 
  # mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>% 
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>% 
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>% 
#  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>% 
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg))
```

```{r Combining Manufacturing datasets}
manufacturing_datasets <- list(ism_pmi, MANEMP, AMTMNO, AMTMVS, IPMAN, CAPGMFS, C307RX1Q020SBEA)
weights <- c(1/2, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12)
weighted_datasets <- mapply(function(df, w, i) {
  df %>%
    mutate(weighted_z = zscore_1yravg * w) %>%
    select(date, weighted_z) %>%
    rename(!!paste0("weighted_z_", i) := weighted_z)
}, manufacturing_datasets, weights, seq_along(manufacturing_datasets), SIMPLIFY = FALSE)

goal_one_tracker <- Reduce(function(x, y) full_join(x, y, by = "date"), weighted_datasets)

goal_one_tracker <- goal_one_tracker %>%
  mutate(total_weighted_z = rowSums(select(., starts_with("weighted_z_")), na.rm = TRUE))

goal_one_tracker %>% 
  filter(date > "2021-01-19") %>% 
  filter(date < "2025-04-30") %>% 
  ggplot(aes(x = date, y = total_weighted_z)) +
  geom_line(size = 1) +
  geom_point() +
  geom_vline(xintercept = important_dates, 
             color = "red", linetype = "dashed", size = 1)
```
```{r}
adherence <- read_csv("trump_tariff_tracker/Data/TTT_Countries.csv")
adherence %>% 
  group_by(Adherence) %>% 
  summarise(Percentage = sum(`GDP Percentage`)) 
```

```{r U5 Unemployment}
U5RATE <- fredr( 
  series_id = "U5RATE",
  observation_start = as.Date("2010-01-01"))
U5RATE$date <- ymd(U5RATE$date)

U5RATE <- U5RATE %>%  
   select(-realtime_start, -realtime_end) %>%  
   mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>%  
   mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>%  
   mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>%  
   mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>%  
   mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)*-1) %>%  
   mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg)*-1) 

U5RATE %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = value)) + 
   geom_point(aes(y = value_10yravg), color = "green") + 
   geom_point(aes(y = value_1yravg), color = "blue") + 
   geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7" 
   geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) + 
   geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Current Data` = "black", 
     `Long Term (10year) Average` = "green", 
     `Short Term (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Monthly Reporting", y = "Percent, Seasonally Adjusted", title = "Unemployment Rate", caption = "U5 Unemployment Rate", color = "Legend") + 
   scale_y_comma() 

 U5RATE %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = zscore_10yravg), color = "green") + 
   geom_point(aes(y = zscore_1yravg), color = "blue") + 
   geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) + 
   geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Z score (10year) Average` = "green", 
     `Z score (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Date", y = "Z score", title = "Z score", color = "Near or Long Term Z score")  
```
```{r Real PCE per capita}
A794RX0Q048SBEA <- fredr( 
  series_id = "A794RX0Q048SBEA",
  observation_start = as.Date("2010-01-01"))
A794RX0Q048SBEA$date <- ymd(A794RX0Q048SBEA$date)

A794RX0Q048SBEA <- A794RX0Q048SBEA %>%  
  select(-realtime_start, -realtime_end) %>% 
  mutate(month_seq = purrr::map(date, ~ seq(.x, by = "1 month", length.out = 3))) %>%
  unnest(month_seq) %>%
  select(-date) %>% 
  rename(date = month_seq) %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg)) 

A794RX0Q048SBEA %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = value)) + 
   geom_point(aes(y = value_10yravg), color = "green") + 
   geom_point(aes(y = value_1yravg), color = "blue") + 
   geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7" 
   geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) + 
   geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Current Data` = "black", 
     `Long Term (10year) Average` = "green", 
     `Short Term (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Quarterly Reporting", y = "Chained 2017 Dollars", title = "Real Personal Consumption Expenditures per Capita", caption = "Seasonally adjusted annual rate", color = "Legend") + 
   scale_y_comma() 

 A794RX0Q048SBEA %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = zscore_10yravg), color = "green") + 
   geom_point(aes(y = zscore_1yravg), color = "blue") + 
   geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) + 
   geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Z score (10year) Average` = "green", 
     `Z score (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Date", y = "Z score", title = "Z score", color = "Near or Long Term Z score")  
```
```{r Median usual weekly real earnings}
LES1252881600Q <- fredr( 
  series_id = "LES1252881600Q",
  observation_start = as.Date("2010-01-01"))
LES1252881600Q$date <- ymd(LES1252881600Q$date)

LES1252881600Q <- LES1252881600Q %>%  
  select(-realtime_start, -realtime_end) %>% 
  mutate(month_seq = purrr::map(date, ~ seq(.x, by = "1 month", length.out = 3))) %>%
  unnest(month_seq) %>%
  select(-date) %>% 
  rename(date = month_seq) %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg)) 

LES1252881600Q %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = value)) + 
   geom_point(aes(y = value_10yravg), color = "green") + 
   geom_point(aes(y = value_1yravg), color = "blue") + 
   geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7" 
   geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) + 
   geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Current Data` = "black", 
     `Long Term (10year) Average` = "green", 
     `Short Term (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Quarterly Reporting", y = "1982-84 CPI Adjusted Dollars", title = "Median usual weekly real earnings", caption = "Seasonally adjusted", color = "Legend") + 
   scale_y_comma() 

 LES1252881600Q %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = zscore_10yravg), color = "green") + 
   geom_point(aes(y = zscore_1yravg), color = "blue") + 
   geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) + 
   geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Z score (10year) Average` = "green", 
     `Z score (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Date", y = "Z score", title = "Z score", color = "Near or Long Term Z score")  
```

```{r Consumer Sentiment}
UMCSENT <- fredr( 
  series_id = "UMCSENT",
  observation_start = as.Date("2010-01-01"))
UMCSENT$date <- ymd(UMCSENT$date)

UMCSENT <- UMCSENT %>%  
  select(-realtime_start, -realtime_end) %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg)) 

UMCSENT %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = value)) + 
   geom_point(aes(y = value_10yravg), color = "green") + 
   geom_point(aes(y = value_1yravg), color = "blue") + 
   geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7" 
   geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) + 
   geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Current Data` = "black", 
     `Long Term (10year) Average` = "green", 
     `Short Term (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Monthly Reporting", y = "Units: Index 1966 (Q1) = 100", title = "Consumer Sentiment", caption = "Not Seasonally adjusted", color = "Legend") + 
   scale_y_comma() 

 UMCSENT %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = zscore_10yravg), color = "green") + 
   geom_point(aes(y = zscore_1yravg), color = "blue") + 
   geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) + 
   geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Z score (10year) Average` = "green", 
     `Z score (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Date", y = "Z score", title = "Z score", color = "Near or Long Term Z score")  
```

```{r Median CPI}
MEDCPIM158SFRBCLE <- fredr( 
  series_id = "MEDCPIM158SFRBCLE",
  observation_start = as.Date("2010-01-01"))
MEDCPIM158SFRBCLE$date <- ymd(MEDCPIM158SFRBCLE$date)

MEDCPIM158SFRBCLE <- MEDCPIM158SFRBCLE %>%  
  select(-realtime_start, -realtime_end) %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)*-1) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg)*-1) 

MEDCPIM158SFRBCLE %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = value)) + 
   geom_point(aes(y = value_10yravg), color = "green") + 
   geom_point(aes(y = value_1yravg), color = "blue") + 
   geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7" 
   geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) + 
   geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Current Data` = "black", 
     `Long Term (10year) Average` = "green", 
     `Short Term (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Monthly Reporting", y = "Percent Change at Annual Rate", title = "Median Consumer Price Index (inflation)", caption = "Seasonally adjusted", color = "Legend") + 
   scale_y_comma() 

 MEDCPIM158SFRBCLE %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = zscore_10yravg), color = "green") + 
   geom_point(aes(y = zscore_1yravg), color = "blue") + 
   geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) + 
   geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Z score (10year) Average` = "green", 
     `Z score (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Date", y = "Z score", title = "Z score", color = "Near or Long Term Z score")  
```
```{r Financial Stress Index}
STLFSI4 <- fredr( 
  series_id = "STLFSI4",
  observation_start = as.Date("2010-01-01"))
STLFSI4$date <- ymd(STLFSI4$date)

STLFSI4 <- STLFSI4 %>%  
  select(-realtime_start, -realtime_end) %>% 
  mutate(date = floor_date(date, "month")) %>%
  group_by(date) %>%
  summarise(value = mean(value), .groups = "drop") %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)*-1) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg)*-1) 

STLFSI4 %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = value)) + 
   geom_point(aes(y = value_10yravg), color = "green") + 
   geom_point(aes(y = value_1yravg), color = "blue") + 
   geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7" 
   geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) + 
   geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Current Data` = "black", 
     `Long Term (10year) Average` = "green", 
     `Short Term (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Weekly Reporting", y = "Index", title = "Financial Stress Index", caption = "Not Seasonally adjusted", color = "Legend") + 
   scale_y_comma() 

 STLFSI4 %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = zscore_10yravg), color = "green") + 
   geom_point(aes(y = zscore_1yravg), color = "blue") + 
   geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) + 
   geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Z score (10year) Average` = "green", 
     `Z score (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Date", y = "Z score", title = "Z score", color = "Near or Long Term Z score")  
```

```{r Balance of Trade}
BOPGSTB <- fredr( 
  series_id = "BOPGSTB",
  observation_start = as.Date("2010-01-01"))
BOPGSTB$date <- ymd(BOPGSTB$date)

BOPGSTB <- BOPGSTB %>%  
  select(-realtime_start, -realtime_end) %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg)) 

BOPGSTB %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = value)) + 
   geom_point(aes(y = value_10yravg), color = "green") + 
   geom_point(aes(y = value_1yravg), color = "blue") + 
   geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7" 
   geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) + 
   geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Current Data` = "black", 
     `Long Term (10year) Average` = "green", 
     `Short Term (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Monthly Reporting", y = "Millions of Dollars", title = "Balance of Trade", caption = "Seasonally adjusted", color = "Legend") + 
   scale_y_comma() 

 BOPGSTB %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = zscore_10yravg), color = "green") + 
   geom_point(aes(y = zscore_1yravg), color = "blue") + 
   geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) + 
   geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Z score (10year) Average` = "green", 
     `Z score (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Date", y = "Z score", title = "Z score", color = "Near or Long Term Z score")  
```
```{r}
goal_eight <- ustfd_simple(
   'v1/accounting/mts/mts_table_3',
   fields = c(
     "record_date", "classification_id", "classification_desc","current_month_rcpt_outly_amt"
     ),
   filter = list(
     record_date = c('>=' = '2010-01-01')
   ),
   page_size = 10000
 )
goal_eight <- select(interest_rates$data, -classification_id)
goal_eight <- goal_eight %>% 
  filter(classification_desc %in% c("Customs Duties", "Total Receipts")) %>% 
  pivot_wider(names_from = classification_desc, values_from = current_month_rcpt_outly_amt) %>% 
  mutate(value = (`Customs Duties`/`Total Receipts`)*100) %>% 
  mutate(value_5yravg = rollmean(value, k = 60, fill = NA, align = "right")) %>%  
  mutate(sd_5yravg = rollapply(value, width = 60, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_5yravg = ((value - value_5yravg)/sd_5yravg)) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg)) 
```

```{r}
goal_seven <- ustfd_simple(
   'v2/accounting/od/avg_interest_rates',
   fields = c(
     "record_date","security_type_desc", "security_desc", "avg_interest_rate_amt"
     ),
   filter = list(
     record_date = c('>=' = '2010-01-01')
   ),
   page_size = 10000
 )
goal_seven <- select(goal_seven$data, -security_type_desc)
goal_seven <- goal_seven %>% 
  filter(security_desc %in% c("Treasury Bills", "Treasury Bonds", "Treasury Notes")) %>% 
  pivot_wider(names_from = security_desc, values_from = avg_interest_rate_amt) %>% 
  mutate(value_10yravg = rollmean(`Treasury Bills`, k = 120, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(`Treasury Bills`, width = 120, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(`Treasury Bills`, k = 12, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(`Treasury Bills`, width = 12, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((`Treasury Bills` - value_10yravg)/sd_10yravg)) %>%  
  mutate(zscore_1yravg = ((`Treasury Bills` - value_1yravg)/sd_1yravg)) 
```
```{r}
GDPC1 <- fredr( 
  series_id = "GDPC1",
  observation_start = as.Date("2010-01-01"))
GDPC1$date <- ymd(GDPC1$date)

A091RC1Q027SBEA <- fredr( 
  series_id = "A091RC1Q027SBEA",
  observation_start = as.Date("2010-01-01"))
A091RC1Q027SBEA$date <- ymd(A091RC1Q027SBEA$date)

ggplot()

FGCRIPRGDP <- A091RC1Q027SBEA %>% 
  rename(payment_value = value) %>% 
  full_join(GDPC1, by = join_by(date)) %>% 
  select(-realtime_start.y, -realtime_start.x, -realtime_end.x, -realtime_end.y, -series_id.x, -series_id.y) %>% 
  rename(gdp_value = value) %>% 
  mutate(value = payment_value/gdp_value) %>% 
  mutate(value_10yravg = rollmean(value, k = 30, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value, width = 30, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 3, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 3, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg)) 
```

```{r Nominal Broad US Dollar Index}
DTWEXBGS <- fredr( 
  series_id = "DTWEXBGS",
  observation_start = as.Date("2010-01-01"))
DTWEXBGS$date <- ymd(DTWEXBGS$date)

DTWEXBGS <- DTWEXBGS %>%  
  select(-realtime_start, -realtime_end) %>% 
  mutate(date = floor_date(date, "month")) %>%
  group_by(date) %>%
  drop_na(value) %>% 
  summarise(value = mean(value), .groups = "drop") %>% 
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)*-1) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg)*-1) 

DTWEXBGS %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = value)) + 
   geom_point(aes(y = value_10yravg), color = "green") + 
   geom_point(aes(y = value_1yravg), color = "blue") + 
   geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7" 
   geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) + 
   geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Current Data` = "black", 
     `Long Term (10year) Average` = "green", 
     `Short Term (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Daily Reporting", y = "Index Jan 2006 = 100", title = "Nominal Broad U.S. Dollar Index", caption = "Not seasonally adjusted", color = "Legend") + 
   scale_y_comma() 

 DTWEXBGS %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = zscore_10yravg), color = "green") + 
   geom_point(aes(y = zscore_1yravg), color = "blue") + 
   geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) + 
   geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) + 
   geom_text_repel(
     data = slice_tail(DTWEXBGS, n = 1), aes(y = zscore_1yravg, label = format(date, "%B %d, %y")), size = 3, nudge_x = -300) +
   scale_color_manual(values = c( 
     `Z score (10year) Average` = "green", 
     `Z score (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Date", y = "Z score", title = "Z score", color = "Near or Long Term Z score")  
```

```{r Military Spending}
gdp <- read_csv("trump_tariff_tracker/Data/gdp.csv")
milex <- read_csv("trump_tariff_tracker/Data/sipri_gdp.csv")
gdp <- gdp %>% 
  pivot_longer(cols = starts_with("20"),
               names_to = "Year",
               values_to = "GDP")
milex <- milex %>% 
  pivot_longer(cols = starts_with("20"),
               names_to = "Year",
               values_to = "Milex")

military_spending <- gdp %>% 
  left_join(milex) %>% 
  mutate(GDP = GDP*1000000000) %>% 
  mutate(Milex = Milex*1000000)

military_spending <- military_spending %>% 
  group_by(Year) %>% 
  summarise(GDP = mean(GDP),
            Milex = mean(Milex)) %>%
  mutate(Share = Milex/GDP)
military_spending$Year <- as.numeric(military_spending$Year) 

military_spending %>% 
  ggplot(aes(x = Year, y = Share)) +
  geom_line()
```

```{r IMF COFER}
COFER <- load_datasets("COFER")
# COFER$dimensions$freq
# COFER$dimensions$ref_area
# COFER$dimensions$indicator
COFER <- COFER$get_series(freq = "Q", ref_area = "W00")
COFER$TIME_PERIOD <- as.Date(as.yearqtr(COFER$TIME_PERIOD, format = "%Y-Q%q"))
COFER <- COFER %>% 
  rename(date = TIME_PERIOD) %>% 
  filter(date > "2010-01-19") %>% 
  select(date, ends_with("USDRT_PT")) %>% 
  rename(value = Q.W00.RAXGFXARUSDRT_PT) %>% 
  mutate(value = as.numeric(value)) %>% 
  mutate(value_10yravg = rollmean(value, k = 30, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value, width = 30, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 3, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 3, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg)) 

COFER %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = value)) + 
   geom_point(aes(y = value_10yravg), color = "green") + 
   geom_point(aes(y = value_1yravg), color = "blue") + 
   geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7" 
   geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) + 
   geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Current Data` = "black", 
     `Long Term (10year) Average` = "green", 
     `Short Term (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Quarterly Reporting", y = "Percentage", title = "Official Foreign Exchange Reserves by Currency", color = "Legend") + 
   scale_y_comma() 

 COFER %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = zscore_10yravg), color = "green") + 
   geom_point(aes(y = zscore_1yravg), color = "blue") + 
   geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) + 
   geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Z score (10year) Average` = "green", 
     `Z score (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Date", y = "Z score", title = "Z score", color = "Near or Long Term Z score")  
```
```{r}
IntlPayments_qtr <- IntlPayments %>% 
  mutate(quarter = as.yearqtr(date)) %>% 
  group_by(quarter) %>% 
  summarise(value_qtr = mean(value), .groups = "drop") %>% 
  mutate(date_qtr = as.Date(quarter + 0.25, frac = 0)) %>% 
  select(-quarter) %>% 
  mutate(value_10yravg = rollmean(value_qtr, k = 40, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value_qtr, width = 40, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_2yravg = rollmean(value_qtr, k = 8, fill = NA, align = "right")) %>%  
  mutate(sd_2yravg = rollapply(value_qtr, width = 8, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value_qtr - value_10yravg)/sd_10yravg)) %>%  
  mutate(zscore_2yravg = ((value_qtr - value_2yravg)/sd_2yravg)) %>% 
  rename(value = value_qtr) %>% 
  rename(date = date_qtr) 
IntlPayments_qtr$date <- ymd(IntlPayments_qtr$date)
write_csv(IntlPayments_qtr, "trump_tariff_tracker/Data/IntlPayments_qtr.csv")
```

```{r}
IntlPayments <- read_csv("trump_tariff_tracker/Data/IntlPayments.csv")
IntlPayments$date <- mdy(IntlPayments$date)
IntlPayments <- IntlPayments %>%  
  mutate(value_10yravg = rollmean(value, k = 120, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value, width = 120, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 12, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 12, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg)) 
write_csv(IntlPayments, "trump_tariff_tracker/Data/IntlPayments.csv")


IntlPayments %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = value)) + 
   geom_point(aes(y = value_10yravg), color = "green") + 
   geom_point(aes(y = value_1yravg), color = "blue") + 
   geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7" 
   geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) + 
   geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Current Data` = "black", 
     `Long Term (10year) Average` = "green", 
     `Short Term (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Monthly Reporting", y = "Percentage", title = "International Payments denominated in USD", color = "Legend") + 
   scale_y_comma() 

 IntlPayments %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = zscore_10yravg), color = "green") + 
   geom_point(aes(y = zscore_1yravg), color = "blue") + 
   geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) + 
   geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Z score (10year) Average` = "green", 
     `Z score (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Date", y = "Z score", title = "Z score", color = "Near or Long Term Z score") 
```

```{r Loans denominated by USD}
usd_loans_url = c("https://stats.bis.org/api/v2/data/dataflow/BIS/WS_LBS_D_PUB/1.0/Q.S.L.G.USD.A.5J.A.5A.A.5J.N?format=csv")

usd_loans_data = list()

for (i in 1:length(usd_loans_url)) {
  usd_loans_data[[i]] <- read.csv(usd_loans_url[i])
}

usd_loans = rbind(usd_loans_data)

usd_loans <- usd_loans["usd_loans_data", 1][["usd_loans_data"]]

total_loans_url <- c("https://stats.bis.org/api/v2/data/dataflow/BIS/WS_LBS_D_PUB/1.0/Q.S.L.G.TO1.A.5J.A.5A.A.5J.N?format=csv")

total_loans_data = list()

for (i in 1:length(total_loans_url)) {
  total_loans_data[[i]] <- read.csv(total_loans_url[i])
}

total_loans <- rbind(total_loans_data)
total_loans <- total_loans["total_loans_data", 1][["total_loans_data"]]

usd_loans <- usd_loans %>% 
  select(TIME_PERIOD, OBS_VALUE) %>% 
  rename(USD = OBS_VALUE)

total_loans <- total_loans %>% 
  select(TIME_PERIOD, OBS_VALUE) %>% 
  rename(Total = OBS_VALUE)

loans_currency <- usd_loans %>% 
  left_join(total_loans) 

loans_currency$TIME_PERIOD <- as.Date(as.yearqtr(loans_currency$TIME_PERIOD, format = "%Y-Q%q"))
loans_currency <- loans_currency %>% 
  rename(date = TIME_PERIOD) %>% 
  filter(date > "2010-01-19") %>% 
  mutate(value = USD/Total) %>% 
  mutate(value_10yravg = rollmean(value, k = 30, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value, width = 30, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 4, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 4, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg))

loans_currency %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = value)) + 
   geom_point(aes(y = value_10yravg), color = "green") + 
   geom_point(aes(y = value_1yravg), color = "blue") + 
   geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7" 
   geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) + 
   geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Current Data` = "black", 
     `Long Term (10year) Average` = "green", 
     `Short Term (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Quarterly Reporting", y = "Percentage", title = "Cross-border total liabilities of banks", color = "Legend") 

 loans_currency %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = zscore_10yravg), color = "green") + 
   geom_point(aes(y = zscore_1yravg), color = "blue") + 
   geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) + 
   geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Z score (10year) Average` = "green", 
     `Z score (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Date", y = "Z score", title = "Z score", color = "Near or Long Term Z score")
```

```{r debt denominated by USD}
usd_debt_url = c("https://stats.bis.org/api/v2/data/dataflow/BIS/WS_DEBT_SEC2_PUB/1.0/Q.3P.3P.1.1.C.A.A.USD.A.A.A.A.A.I?format=csv")

usd_debt_data = list()

for (i in 1:length(usd_debt_url)) {
  usd_debt_data[[i]] <- read.csv(usd_debt_url[i])
}

usd_debt = rbind(usd_debt_data)

usd_debt <- usd_debt["usd_debt_data", 1][["usd_debt_data"]]

total_debt_url <- c("https://stats.bis.org/api/v2/data/dataflow/BIS/WS_DEBT_SEC2_PUB/1.0/Q.3P.3P.1.1.C.A.A.TO1.A.A.A.A.A.I?format=csv")

total_debt_data = list()

for (i in 1:length(total_debt_url)) {
  total_debt_data[[i]] <- read.csv(total_debt_url[i])
}

total_debt <- rbind(total_debt_data)
total_debt <- total_debt["total_debt_data", 1][["total_debt_data"]]

usd_debt <- usd_debt %>% 
  select(TIME_PERIOD, OBS_VALUE) %>% 
  rename(USD = OBS_VALUE)

total_debt <- total_debt %>% 
  select(TIME_PERIOD, OBS_VALUE) %>% 
  rename(Total = OBS_VALUE)

debt_currency <- usd_debt %>% 
  left_join(total_debt) 

debt_currency$TIME_PERIOD <- as.Date(as.yearqtr(debt_currency$TIME_PERIOD, format = "%Y-Q%q"))
debt_currency <- debt_currency %>% 
  rename(date = TIME_PERIOD) %>% 
  filter(date > "2010-01-19") %>% 
  mutate(value = USD/Total) %>% 
  mutate(value_10yravg = rollmean(value, k = 30, fill = NA, align = "right")) %>%  
  mutate(sd_10yravg = rollapply(value, width = 30, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(value_1yravg = rollmean(value, k = 4, fill = NA, align = "right")) %>%  
  mutate(sd_1yravg = rollapply(value, width = 4, FUN = sd, fill = NA, align = "right")) %>%  
  mutate(zscore_10yravg = ((value - value_10yravg)/sd_10yravg)) %>%  
  mutate(zscore_1yravg = ((value - value_1yravg)/sd_1yravg))

debt_currency %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = value)) + 
   geom_point(aes(y = value_10yravg), color = "green") + 
   geom_point(aes(y = value_1yravg), color = "blue") + 
   geom_line(aes(y = value, color = "Current Data"), size = 1) + #color = ", #A7C7E7" 
   geom_line(aes(y = value_10yravg, color = "Long Term (10year) Average"), size = 1) + 
   geom_line(aes(y = value_1yravg, color = "Short Term (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Current Data` = "black", 
     `Long Term (10year) Average` = "green", 
     `Short Term (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Quarterly Reporting", y = "US dollar (Millions)", title = "Debt Securities Issuance by Currency", color = "Legend") 

 debt_currency %>%  
   filter(date > "2021-01-19") %>%  
   ggplot(aes(x = date)) + 
   geom_point(aes(y = zscore_10yravg), color = "green") + 
   geom_point(aes(y = zscore_1yravg), color = "blue") + 
   geom_line(aes(y = zscore_10yravg, color = "Z score (10year) Average"), size = 1) + 
   geom_line(aes(y = zscore_1yravg, color = "Z score (1year) Average"), size = 1) + 
   scale_color_manual(values = c( 
     `Z score (10year) Average` = "green", 
     `Z score (1year) Average` = "blue" 
   )) + 
   geom_vline(xintercept = important_dates,  
              color = "red", linetype = "dashed", size = 1) + 
   labs(x = "Date", y = "Z score", title = "Z score", color = "Near or Long Term Z score")
```
```{r}
adherence <- read_csv("trump_tariff_tracker/Data/TTT_Countries.csv")

adherence$Date <- mdy(adherence$Date)
all_quarters <- seq(floor_date(min(adherence$Date), "quarter"),
                    floor_date(max(adherence$Date), "quarter"),
                    by = "quarter")

adherence <- adherence %>% 
  mutate(date = floor_date(Date, "quarter")) %>%
  group_by(Country) %>%
  complete(date = all_quarters) %>%  
  arrange(Country, date) %>%
  fill(Adherence, `GDP Percentage`, .direction = "down") %>%
  group_by(date, Adherence) %>% 
  summarise(`GDP Percentage` = sum(`GDP Percentage`), .groups = "drop") %>%  
  arrange(date) %>% 
  pivot_wider(names_from = Adherence, values_from = `GDP Percentage`) %>% 
  mutate(Stable = No + Partial)
write_csv(adherence, "./trump_tariff_tracker/Data/goal_three_data.csv")
```
```{r}
adherence_countries <- read_csv("Data/TTT_Countries.csv")
green_countries <- adherence_countries %>% 
  filter(Adherence == "Full") %>% 
  group_by(Country) %>% 
  slice_tail(n = 1) %>% 
  arrange(desc(GDP))
```




